#!/bin/bash

if [ "$EUID" -ne "0" ]; then
	echo "Please, run this script as sudo. Thanks!!";
	exit 1;
fi

./docker-install-vm/install-docker;

if [ "$?" -eq "0" ]; then
	echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list;
	apt-get update;
	if [ "$?" -eq "0" ]; then
		apt-get install kubeadm;
		if [ "$?" -eq "0" ]; then
			kubeadm reset -f;
			echo "Everything's fine. Docker and Kubenertes installed successfuly."
			exit 0;
		else
			echo "Failed to install kubeadm";
		fi
	else
		echo "Failed to run apt-get update";
	fi
else
	echo "Failed to install docker."
fi
